######################################
#                                    #
#       COMMAND CONFIGURATION        #
#                                    #
######################################

#-------------------------------------------------------------------------
#    CHECK OUR DOCUMENTATION FOR DETAILED DESCRIPTIONS FOR EACH SETTING
#                     https://docs.corebot.dev
#-------------------------------------------------------------------------

######################################
#                                    #
#     ENABLED/DISABLED COMMANDS      #
#                                    #
######################################

Enabled:
  8ball: false
  accept: true
  addinvites: true
  announce: true
  autoannounce: true
  achievement: false
  addon: true
  avatar: true
  add: true
  application: false
  apply: false
  buy: false
  bnote: false
  backup: true
  botinfo: true
  bugreport: true
  ban: true
  bans: true
  blacklist: true
  boosters: true
  code: true
  coins: false
  cointop: false
  closeall: true
  createrole: true
  coinflip: false
  connect4: false
  command: true
  commandchannels: true
  clear: true
  channelinfo: true
  close: true
  daily: false
  deleterole: true
  deny: true
  edit: true
  embed: true
  eval: true
  filter: true
  fix: true
  givecoins: false
  givelevels: true
  giverole: true
  givexp: true
  gamestats: true
  gametop: false
  gcreate: true
  gdelete: true
  gedit: true
  giveaway: true
  greroll: true
  gschedule: true
  gstop: true
  google: false
  help: true
  history: true
  ip: true
  invite: true
  invites: true
  invitetop: true
  join: true
  key: true
  kick: true
  level: true
  leveltop: true
  links: true
  lock: true
  lockserver: true
  movevc: true
  msg: true
  math: false
  modules: true
  minecraftuser: false
  mute: true
  mutelist: true
  msgtop: true
  musicemojis: false
  nuke: true
  new: true
  pay: false
  paste: true
  ping: true
  prefix: true
  profile: true
  play: false
  pause: false
  queue: false
  react: true
  reactfor: true
  removeinvites: true
  rolemenu: true
  rockpaperscissors: false
  rolldice: false
  rank: true
  remindme: true
  report: true
  reset: true
  removewarn: true
  roleinfo: true
  reload: true
  remove: true
  rename: true
  resume: true
  shop: false
  slots: false
  saccept: true
  say: true
  sdeny: true
  simplement: true
  snote: true
  sudo: true
  suggest: true
  setactivity: true
  setcoins: false
  setexp: true
  setlevel: true
  setprefix: true
  setstatus: true
  setup: true
  server: true
  status: true
  slowmode: true
  serverinfo: true
  staffhelp: true
  stop: true
  skip: true
  takecoins: true
  takelevels: true
  takerole: true
  takexp: true
  topic: false
  tictactoe: false
  tempchannel: true
  tempban: true
  tempmute: true
  tickets: true
  update: true
  updaterolemenus: true
  unban: true
  unblacklist: true
  unlock: true
  unlockserver: true
  unmute: true
  userinfo: true
  vote: true
  verify: true
  verification: true
  vctop: true
  weekly: false
  work: false
  warn: true
  warnings: true

######################################
#                                    #
#        COMMAND PERMISSIONS         #
#                                    #
######################################

Inheritance: true

Permissions:
  8ball:
    - "@everyone"
  accept:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  addinvites:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  announce:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  autoannounce:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  achievement:
    - "@everyone"
  addon:
    - "ğŸ‘‘ã€¡Owner"
  avatar:
    - "@everyone"
  add:
    - "@everyone"
  application:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  apply:
    - "@everyone"
  buy:
    - "@everyone"
  bnote:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  backup:
    - "ğŸ‘‘ã€¡Owner"
  botinfo:
    - "ğŸ‘‘ã€¡Owner"
  bugreport:
    - "@everyone"
  ban:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  bans:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  blacklist:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  boosters:
    - "@everyone"
  code:
    - "Owner"
  coins:
    - "@everyone"
  cointop:
    - "@everyone"
  closeall:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  createrole:
    - "ğŸ‘‘ã€¡Managers"
  coinflip:
    - "@everyone"
  connect4:
    - "@everyone"
  command:
    - "ğŸ‘‘ã€¡Owner"
  commandchannels:
    - "ğŸ‘‘ã€¡Owner"
  clear:
    - "ğŸ‘‘ã€¡Managers"
  channelinfo:
    - "@everyone"
  close:
    - "@everyone"
  daily:
    - "@everyone"
  deleterole:
    - "ğŸ‘‘ã€¡Managers"
  deny:
    - "ğŸ‘‘ã€¡Managers"
  edit:
    - "ğŸ‘‘ã€¡Managers"
  embed:
    - "Owner"
  eval:
    - "266939010272854016"
    - ""
  filter:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  fix:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  givecoins:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  givelevels:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  giverole:
    - "ğŸ‘‘ã€¡Managers"
  givexp:
    - "ğŸ‘‘ã€¡Managers"
  gamestats:
    - "@everyone"
  gametop:
    - "@everyone"
  gcreate:
    - "ğŸ‘‘ã€¡Managers"
  gdelete:
    - "ğŸ‘‘ã€¡Managers"
  gedit:
    - "ğŸ‘‘ã€¡Managers"
  giveaway:
    - "ğŸ‘‘ã€¡Managerss"
  greroll:
    - "ğŸ‘‘ã€¡Managers"
  gschedule:
    - "ğŸ‘‘ã€¡Managers"
  gstop:
    - "ğŸ‘‘ã€¡Managers"
  google:
    - "@everyone"
  help:
    - "@everyone"
  history:
    - "ğŸ‘®ã€¡Staff"
  ip:
    - "@everyone"
  invite:
    - "@everyone"
  invites:
    - "@everyone"
  invitetop:
    - "@everyone"
  join:
    - "@everyone"
  key:
    - "Owner"
  kick:
    - "ğŸ‘®ã€¡Staff"
  level:
    - "@everyone"
  leveltop:
    - "@everyone"
  links:
    - "@everyone"
  lock:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  lockserver:
    - "ğŸ‘‘ã€¡Managers"
  movevc:
    - "Senior Staff"
  msg:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  math:
    - "@everyone"
  modules:
    - "ğŸ‘‘ã€¡Owner"
  minecraftuser:
    - "@everyone"
  mute:
    - "ğŸ‘®ã€¡Staff"
  mutelist:
    - "ğŸ‘®ã€¡Staff"
  msgtop:
    - "@everyone"
  musicemojis:
    - "ğŸ‘®ã€¡Staff"
  nuke:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  new:
    - "@everyone"
  pay:
    - "@everyone"
  paste:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  ping:
    - "@everyone"
  prefix:
    - "@everyone"
  profile:
    - "@everyone"
  play:
    - "@everyone"
  pause:
    - "@everyone"
  queue:
    - "@everyone"
  react:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  reactfor:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  removeinvites:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  rolemenu:
    - "ğŸ‘‘ã€¡Managers"
  rockpaperscissors:
    - "@everyone"
  rolldice:
    - "@everyone"
  rank:
    - "@everyone"
  remindme:
    - "@everyone"
  report:
    - "@everyone"
  reset:
    - "ğŸ‘‘ã€¡Owner"
  removewarn:
    - "ğŸ‘‘ã€¡Managers"
  roleinfo:
    - "@everyone"
  reload:
    - "Owner"
  remove:
    - "@everyone"
  rename:
    - "@everyone"
  resume:
    - "@everyone"
  shop:
    - "@everyone"
  slots:
    - "@everyone"
  saccept:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  say:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  sdeny:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  simplement:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  snote:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  sudo:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  suggest:
    - "@everyone"
  setactivity:
    - "ğŸ‘‘ã€¡Owner"
  setcoins:
    - "ğŸ‘‘ã€¡Owner"
  setexp:
    - "ğŸ‘‘ã€¡Owner"
  setlevel:
    - "ğŸ‘‘ã€¡Owner"
  setprefix:
    - "ğŸ‘‘ã€¡Owner"
  setstatus:
    - "ğŸ‘‘ã€¡Owner"
  setup:
    - "ğŸ‘‘ã€¡Owner"
  server:
    - "@everyone"
  status:
    - "@everyone"
  slowmode:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  serverinfo:
    - "@everyone"
  staffhelp:
    - "ğŸ‘‘ã€¡Managers"
  stop:
    - "@everyone"
  skip:
    - "@everyone"
  takecoins:
    - "ğŸ‘‘ã€¡Managers"
  takelevels:
    - "ğŸ‘‘ã€¡Managers"
  takerole:
    - "ğŸ‘‘ã€¡Managers"
  takexp:
    - "ğŸ‘‘ã€¡Managers"
  topic:
    - "ğŸ‘‘ã€¡Managers"
  tictactoe:
    - "@everyone"
  tempchannel:
    - "@everyone"
  tempban:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  tempmute:
    - "Mod"
  tickets:
    - "@everyone"
  update:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  updaterolemenus:
    - "ğŸ‘‘ã€¡Owner"
  unban:
    - "ğŸ‘‘ã€¡Managers"
  unblacklist:
    - "ğŸ‘‘ã€¡Managers"
  unlock:
    - "ğŸ‘¨â€ğŸš’ã€¡Senior Staff"
  unlockserver:
    - "ğŸ‘‘ã€¡Managers"
  unmute:
    - "Mod"
  userinfo:
    - "@everyone"
  vote:
    - "ğŸ‘‘ã€¡Managers"
  verify:
    - "@everyone"
  verification:
    - "ğŸ‘‘ã€¡Owner"
  vctop:
    - "@everyone"
  weekly:
    - "@everyone"
  work:
    - "@everyone"
  warn:
    - "ğŸ‘®ã€¡Staff"
  warnings:
    - "ğŸ‘®ã€¡Staff"

######################################
#                                    #
#          COMMAND ALIASES           #
#                                    #
######################################

Aliases:
  accept:
    - "accepted"
  announce:
    - "announcement"
  autoannounce:
    - "aa"
  add:
    - "adduser"
  application:
    - "applicationmenu"
    - "app"
  apply:
    - "application"
  bnote:
    - "bugreportnote"
    - "bugnote"
    - "bmsg"
    - "bugmessage"
  backup:
    - "backupserver"
  bugreport:
    - "bug"
  ban:
    - "idban"
    - "banid"
  bans:
    - "banlist"
  coins:
    - "bal"
    - "balance"
  cointop:
    - "coinlb"
  coinflip:
    - "flipcoin"
  connect4:
    - "c4"
  command:
    - "commands"
  commandchannels:
    - "cmdchannel"
    - "cmdchannels"
    - "commandchannel"
    - "cc"
  clear:
    - "purge"
    - "clean"
  close:
    - "ticketclose"
    - "closeticket"
  daily:
    - "dailycoins"
  deny:
    - "denied"
  fix:
    - "fixed"
  givecoins:
    - "addcoins"
  givelevels:
    - "givelevel"
    - "addlevel"
    - "addlevels"
  giverole:
    - "addrole"
  givexp:
    - "giveexp"
    - "giveexperience"
  gamestats:
    - "connect4stats"
    - "tictactoestats"
  gcreate:
    - "giveawaycreate"
    - "creategiveaway"
  gdelete:
    - "giveawaydelete"
    - "deletegiveaway"
  giveaway:
    - "giveaways"
  gstop:
    - "gend"
    - "giveawayend"
    - "giveawaystop"
    - "gforcestop"
    - "giveawayforcestop"
  google:
    - "googlesearch"
    - "searchgoogle"
  ip:
    - "serverip"
  join:
    - "connect"
  level:
    - "explevel"
    - "xplevel"
    - "xp"
    - "exp"
    - "experience"
  leveltop:
    - "levellb"
  lockserver:
    - "lockdown"
    - "lockall"
    - "serverlockdown"
    - "lockdownserver"
  msg:
    - "message"
  modules:
    - "module"
  minecraftuser:
    - "mcuser"
    - "mcaccount"
    - "namehistory"
  mutelist:
    - "mutes"
  msgtop:
    - "mtop"
    - "messagestop"
    - "messagetop"
  musicemojis:
    - "music-emojis"
  new:
    - "ticket"
  paste:
    - "haste"
  ping:
    - "latency"
  prefix:
    - "prefixes"
  profile:
    - "stats"
  play:
    - "p"
  queue:
    - "q"
  removeinvites:
    - "delinvites"
    - "reminvites"
  rolemenu:
    - "rolemenus"
    - "reactionrole"
    - "reactionroles"
  rockpaperscissors:
    - "rps"
  rolldice:
    - "roll"
    - "dice"
  remindme:
    - "reminders"
    - "reminder"
    - "remind"
  removewarn:
    - "remwarn"
    - "deletewarn"
    - "delwarn"
  rename:
    - "renameticket"
  shop:
    - "store"
  slots:
    - "slot"
    - "gamble"
  saccept:
    - "suggestaccept"
    - "suggestionaccept"
  sdeny:
    - "sdenied"
  simplement:
    - "simplemented"
    - "implement"
    - "implemented"
  snote:
    - "suggestionnote"
    - "smsg"
    - "suggestionmessage"
  setexp:
    - "setxp"
    - "setexperience"
  setup:
    - "install"
  server:
    - "mcserver"
  status:
    - "serverstatus"
  staffhelp:
    - "shelp"
  stop:
    - "leave"
    - "disconnect"
  skip:
    - "next"
  takecoins:
    - "removecoins"
  takelevels:
    - "takelevel"
    - "removelevel"
    - "removelevels"
  takerole:
    - "removerole"
  takexp:
    - "takeexp"
    - "takeexperience"
  topic:
    - "settopic"
  tictactoe:
    - "tic-tac-toe"
    - "ttt"
  tempchannel:
    - "tc"
  updaterolemenus:
    - "updaterm"
  unban:
    - "idunban"
    - "unbanid"
  unlockserver:
    - "unlockdown"
    - "unlockall"
    - "serverunlockdown"
    - "unlockdownserver"
  userinfo:
    - "whois"
  vote:
    - "poll"
  vctop:
    - "vtop"
    - "voicetopv"
    - "voicechanneltop"
  weekly:
    - "weeklycoins"
  work:
    - "job"

######################################
#                                    #
#        COMMAND DESCRIPTIONS        #
#                                    #
######################################

Descriptions:
  8ball: "Ask the magical 8 ball a question and get an answer"
  accept: "Change a suggestion, bug report, or application to accepted"
  addinvites: "Add bonus invites to a user"
  announce: "Create an announcement"
  autoannounce: "Manage auto announcements"
  achievement: "Generate a minecraft achievement message"
  addon: "Manage your addons"
  avatar: "View a user's avatar"
  add: "Add a user to a ticket."
  application: "Open the application menu and perform actions on an application"
  apply: "Create an application"
  buy: "Purchase an item from the shop"
  bnote: "Send a message in a bug channel"
  backup: "Backup or restore your discord server."
  botinfo: "View info about Corebot"
  bugreport: "Report a bug on the server"
  ban: "Ban a member of the server."
  bans: "View a list of currently banned users"
  blacklist: "Blacklist a user from running all or a specific command"
  boosters: "View the server Nitro boosters"
  code: "Users can use this to determine if you are using a legitimate copy of Corebot."
  coins: "Check how many coins you or another user has"
  cointop: "Check the coin leaderboard"
  closeall: "Close all open tickets"
  createrole: "Create a role on the Discord server"
  coinflip: "Flip a coin"
  connect4: "Connect 4 game"
  command: "Enable or disable a command"
  commandchannels: "Manage the channels commands can be ran in"
  clear: "Clear a certain amount of messages"
  channelinfo: "View info on a channel"
  close: "Close the ticket you are typing in"
  daily: "Get your daily coins"
  deleterole: "Delete a role on the Discord server"
  deny: "Change a suggestion, bug report, or application to denied"
  edit: "Edit a message sent by the bot"
  embed: "Test out an embed from the embeds.yml"
  eval: "Evalute code on the bot (dangerous)"
  filter: "Add, delete, or view the list of filtered words"
  fix: "Change a bug report to fixed"
  givecoins: "Give coins to all or a certain user"
  givelevels: "Give levels to all or a certain user"
  giverole: "Give all or a certain user a role"
  givexp: "Give XP to all or a certain user"
  gamestats: "View a user's game stats"
  gametop: "View who has won the most games"
  gcreate: "Create a giveaway"
  gdelete: "Delete the ongoing giveaway"
  gedit: "Edit a giveaway"
  giveaway: "View the help menu for giveaways"
  greroll: "Create a new set of winners for the giveaway"
  gschedule: "View a list of giveaways and when they end"
  gstop: "Force a giveaway to end"
  google: "Search for some thing on google"
  help: "View the command help menu"
  history: "View the punishment history of a user"
  ip: "View the Minecraft server's IP"
  invite: "Create an invite"
  invites: "View your invites"
  invitetop: "View the invite leaderboard"
  join: "Make the bot join your voice channel"
  key: "Install a corebot addon"
  kick: "Kick a user in the Discord server"
  level: "Check your current level"
  leveltop: "Check the experience leaderboard"
  links: "View links related to the Discord server"
  lock: "Lock the channel so users cannot send messages"
  lockserver: "Lock the channel so users cannot send messages"
  movevc: "Move all members from a/your current voice channel to another one"
  msg: "Message all or certain users"
  math: "Evaluate a math equation"
  modules: "Enable or disable a module"
  minecraftuser: "View minecraft account information"
  mute: "Mute a user in the Discord server"
  mutelist: "View a list of currently muted users"
  msgtop: "Check the message count leaderboard"
  musicemojis: "Create the emojis for music"
  nuke: "Delete a channel and recreate it"
  new: "Create a ticket"
  pay: "Send money to a user"
  paste: "Upload text to the paste site"
  ping: "Check the bot's latency"
  prefix: "Check the bot's prefix"
  profile: "View a user's profile"
  play: "Play music in a voice channel"
  pause: "Pause the currently playing song"
  queue: "View the list of queued songs"
  react: "React to a message with an emoji"
  reactfor: "Create a react for ticket or react for application embed"
  removeinvites: "Remove bonus invites from a user"
  rolemenu: "Send the reaction role menu"
  rockpaperscissors: "Rock paper scissors game"
  rolldice: "Roll a dice"
  rank: "View your rank in the coin and level leaderboard"
  remindme: "Make the bot remind you to do something"
  report: "Report a user in the Discord server"
  reset: "Reset coins or exp of a user"
  removewarn: "Remove a warning from a user"
  roleinfo: "View information on a role"
  reload: "Reload certain aspects of the bot"
  remove: "Remove a user from the ticket you are typing in"
  rename: "Rename a ticket channel"
  resume: "Resume the currently paused song"
  shop: "View the Discord server's shop"
  slots: "Gamble a certain amount of your coins"
  saccept: "Change a suggestion to accepted"
  say: "Make the bot send a certain message"
  sdeny: "Change a suggestion to denied"
  simplement: "Change a suggestion to implemented"
  snote: "Send a message in a suggestion channel"
  sudo: "Send a fake message from another user"
  suggest: "Suggest something for the Discord server"
  setactivity: "Set the bot's activity"
  setcoins: "Set the coins of all or a certain user"
  setexp: "Set the exp of all or a certain user"
  setlevel: "Set the level of all or a certain user"
  setprefix: "Set the bot's prefix"
  setstatus: "Set the bot's status"
  setup: "Create any missing channels and roles for the server"
  server: "View minecraft server information"
  status: "View a Minecraft server's status"
  slowmode: "Turn on or off slowmode"
  serverinfo: "View server information"
  staffhelp: "View the staff command help menu"
  stop: "Stop playing music"
  skip: "Skip to the next song in the queue"
  takecoins: "Take coins from all or a certain user"
  takelevels: "Take levels from all or a certain user"
  takerole: "Take a role from all or a certain user"
  takexp: "Take XP from all or a certain user"
  topic: "Change the topic of a channel"
  tictactoe: "Tic-Tac-Toe game"
  tempchannel: "Manage your temp channel"
  tempban: "Temporarily ban a user on the Discord server"
  tempmute: "Temporarily mute a user on the Discord server"
  tickets: "Get a list of tickets a user has opened"
  update: "Create an update"
  updaterolemenus: "Update all role menus"
  unban: "Unban a user on the Discord server"
  unblacklist: "Unblacklist a user"
  unlock: "Unlock the channel you are typing in"
  unlockserver: "Unlock the server or all channels that are locked"
  unmute: "Unmute a user on the Discord server"
  userinfo: "View your or a certain user's info"
  vote: "Create a poll"
  verify: "Verify that you aren't a bot account"
  verification: "Manage the verification system"
  vctop: "Check the message count leaderboard"
  weekly: "Claim your weekly coins"
  work: "Work at a job to earn coins"
  warn: "Warn a user on the Discord server"
  warnings: "View the warnings of a user on the Discord server"